# Generated by Django 5.2.5 on 2025-10-10 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_rename_texto_comentario_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='autorizador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicaciones.autor'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autorizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicaciones.autorizador'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada')], default='BORRADOR', max_length=20),
        ),
    ]
